# Generated by Django 3.2.6 on 2021-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_education_freeedu'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='FreeEdu',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
